@extends('layouts.admin.app')

@section('title', 'MDP Actions Report')

@section('content')

<div class="container-fluid">

    <div class="d-flex justify-content-between align-items-center mb-4">

        <div>

            <h4 class="fw-bold">

                <i class="bi bi-lightning-charge-fill text-warning me-2"></i>

                MDP Actions Report

            </h4>

            <p class="text-muted mb-0">

                Recommended actions generated by the Markov Decision Process.

            </p>

        </div>

        <div class="btn-group">
            <!--
            <a href="#" class="btn btn-success">

                <i class="bi bi-file-earmark-excel me-1"></i>

                Excel

            </a>

            <a href="#" class="btn btn-danger">

                <i class="bi bi-file-earmark-pdf me-1"></i>

                PDF

            </a>

            <button onclick="window.print()" class="btn btn-secondary">

                <i class="bi bi-printer me-1"></i>

                Print

            </button>
        -->

        </div>

    </div>

    {{-- Filter --}}

    <form method="GET">

        <div class="card shadow-sm mb-4">

            <div class="card-body">

                <div class="row">

                    <div class="col-md-4">

                        <label class="form-label">

                            Period

                        </label>

                        <select name="period_id" class="form-select">

                            @foreach($periods as $period)

                            <option value="{{ $period->id }}" @selected($selectedPeriod==$period->id)>

                                {{ $period->name }}

                            </option>

                            @endforeach

                        </select>

                    </div>

                    <div class="col-md-6">

                        <label class="form-label">

                            Department

                        </label>

                        <select name="department_id" class="form-select">

                            <option value="">

                                All Departments

                            </option>

                            @foreach($departments as $department)

                            <option value="{{ $department->id }}" @selected($selectedDepartment==$department->id)>

                                {{ $department->name }}

                            </option>

                            @endforeach

                        </select>

                    </div>

                    <div class="col-md-2 d-grid">

                        <label>&nbsp;</label>

                        <button class="btn btn-primary">

                            <i class="bi bi-search me-1"></i>

                            Filter

                        </button>

                    </div>

                </div>

            </div>

        </div>

    </form>

    {{-- Summary --}}

    <div class="row mb-4">

        <div class="col-md-3">

            <div class="card border-start border-primary border-4">

                <div class="card-body">

                    <small class="text-muted">

                        Total Employee

                    </small>

                    <h3>

                        {{ $summary['totalEmployee'] }}

                    </h3>

                </div>

            </div>

        </div>

        <div class="col-md-3">

            <div class="card border-start border-success border-4">

                <div class="card-body">

                    <small class="text-muted">

                        Average Reward

                    </small>

                    <h3>

                        {{ number_format($summary['averageReward'],2) }}

                    </h3>

                </div>

            </div>

        </div>

        <div class="col-md-3">

            <div class="card border-start border-warning border-4">

                <div class="card-body">

                    <small class="text-muted">

                        Highest Reward

                    </small>

                    <h3>

                        {{ number_format($summary['maxReward'],2) }}

                    </h3>

                </div>

            </div>

        </div>

        <div class="col-md-3">

            <div class="card border-start border-danger border-4">

                <div class="card-body">

                    <small class="text-muted">

                        Lowest Reward

                    </small>

                    <h3>

                        {{ number_format($summary['minReward'],2) }}

                    </h3>

                </div>

            </div>

        </div>

    </div>

    {{-- Table --}}

    <div class="card shadow-sm">

        <div class="card-header">

            <strong>

                MDP Recommended Actions

            </strong>

        </div>

        <div class="card-body">

            <div class="table-responsive">

                <table class="table table-bordered table-hover align-middle">

                    <thead class="table-light">

                        <tr>

                            <th width="60">#</th>

                            <th>Employee</th>

                            <th>Department</th>

                            <th>Position</th>

                            <th>Current State</th>

                            <th>Recommended Action</th>

                            <th class="text-center">Reward</th>

                        </tr>

                    </thead>

                    <tbody>

                        @forelse($results as $result)

                        <tr>

                            <td>

                                {{ $results->firstItem() + $loop->index }}

                            </td>

                            <td>

                                {{ $result->employee->name }}

                            </td>

                            <td>

                                {{ $result->employee->department->name ?? '-' }}

                            </td>

                            <td>

                                {{ $result->employee->position->name ?? '-' }}

                            </td>

                            <td>

                                @if($result->state)

                                <span class="badge bg-{{ $result->state->color }}">

                                    {{ $result->state->code }}

                                </span>

                                {{ $result->state->name }}

                                @else

                                -

                                @endif

                            </td>

                            <td>

                                @if($result->action)

                                <span class="badge bg-info">

                                    {{ $result->action->code }}

                                </span>

                                {{ $result->action->name }}

                                @else

                                -

                                @endif

                            </td>

                            <td class="text-center">

                                <span class="badge bg-success">

                                    {{ number_format($result->reward,2) }}

                                </span>

                            </td>

                        </tr>

                        @empty

                        <tr>

                            <td colspan="7" class="text-center py-5">

                                <i class="bi bi-lightning-charge display-4 text-muted"></i>

                                <br><br>

                                No MDP action analysis available.

                            </td>

                        </tr>

                        @endforelse

                    </tbody>

                </table>

            </div>

            <div class="mt-3">

                {{ $results->links() }}

            </div>

        </div>

    </div>

</div>

@endsection