<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>Employee Performance Report</title>


    <style>
        @page {
            margin: 20px;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        table th,
        table td {
            border: 1px solid #000;
            padding: 5px;
        }

        table th {
            background: #eeeeee;
            text-align: center;
        }

        .text-center {
            text-align: center;
        }

        .text-right {
            text-align: right;
        }

        .footer {
            margin-top: 50px;
        }

        .signature {
            width: 250px;
            float: right;
            text-align: center;
        }

        .signature .space {
            height: 80px;
        }
    </style>
</head>

<body>

    <table width="100%" style="border:none; margin-bottom:5px;">
        <tr>

            <td width="90" style="border:none;">

                <img src="{{ public_path('assets/images/Makerindo-Logo.png') }}" style="width:164px;">

            </td>

            <td style="border:none; text-align:center;">

                <div style="font-size:22px;font-weight:bold;">
                    PT. MAKERINDO PRIMA SOLUSI
                </div>

                <div style="font-size:13px;">
                    Employee Performance Management System
                </div>

                <div style="font-size:11px;color:#555;">
                    Employee Performance Report
                </div>

            </td>

        </tr>

    </table>

    <hr style="border:2px solid #000;margin-bottom:2px;">
    <hr style="border:0.5px solid #000;margin-top:0;">

    <table width="100%" style="border:none;margin-bottom:15px;">

        <tr>

            <td style="border:none;width:120px;">
                <strong>Report Period</strong>
            </td>

            <td style="border:none;width:10px;">:</td>

            <td style="border:none;">
                {{ $period?->name ?? 'All Periods' }}
            </td>

            <td style="border:none;text-align:right;">
                Printed :
                {{ now()->format('d F Y H:i') }}
            </td>

        </tr>

        <tr>

            <td style="border:none;">
                <strong>Total Employees</strong>
            </td>

            <td style="border:none;">:</td>

            <td style="border:none;">
                {{ $results->count() }} Employee(s)
            </td>

            <td style="border:none;text-align:right;">
                Generated by HR System
            </td>

        </tr>

    </table>
    @php
    $average = 0;
    @endphp

    <table class="report">

        <thead>

            <tr>
                <th width="60">No</th>



                <th>Employee Code</th>

                <th>Employee Name</th>

                <th>Department</th>

                <th>Position</th>

                <th width="40">Average Score</th>

                <th width="40">Final Score</th>
                <th width="50">Rank</th>
                <th width="80">Grade</th>
                <th width="120">Period</th>
            </tr>

        </thead>

        <tbody>

            @forelse($results as $result)

            @php
            $average += $result->final_score;
            @endphp

            <tr>



                <td class="text-center">

                    {{ $loop->iteration }}

                </td>

                <td>

                    {{ $result->employee->employee_code }}

                </td>

                <td>

                    {{ $result->employee->name }}

                </td>

                <td>

                    {{ $result->employee->department?->name }}

                </td>

                <td>

                    {{ $result->employee->position?->name }}

                </td>

                <td class="text-right">

                    {{ number_format($result->average_score,2) }}

                </td>

                <td class="text-right">

                    <strong>

                        {{ number_format($result->final_score,2) }}

                    </strong>

                </td>

                <td class="text-center">

                    {{ $result->grade }}

                </td>
                <td class="text-center">

                    {{ $result->rank }}

                </td>

                <td class="text-center">

                    {{ $result->period->name ?? ''

                    }}

                </td>
            </tr>

            @empty

            <tr>

                <td colspan="9" class="text-center">

                    No data available.

                </td>

            </tr>

            @endforelse

        </tbody>

        @if($results->count())

        <tfoot>

            <tr>

                <th colspan="6" class="text-right">

                    Average Final Score

                </th>

                <th class="text-right">

                    {{ number_format($average / $results->count(),2) }}

                </th>

                <th></th>
                <th></th>
                <th></th>
            </tr>

        </tfoot>

        @endif

    </table>

    <div class="footer">

        <div class="signature">

            <p>

                {{ now()->format('d F Y') }}

            </p>

            <p>

                Human Resources

            </p>

            <div class="space"></div>

            <strong>

                (__________________________)

            </strong>

        </div>

    </div>


</body>

</html>