@extends('layouts.admin.app')

@section('title','ABC Best Solution')

@section('content')

<div class="container-fluid">

    <div class="d-flex justify-content-between align-items-center mb-4">

        <div>

            <h4 class="fw-bold">

                <i class="bi bi-award-fill text-warning me-2"></i>

                ABC Best Solution Report

            </h4>

            <p class="text-muted mb-0">

                Best optimization result generated by the Artificial Bee Colony algorithm.

            </p>

        </div>

        <div class="btn-group">
            <!--
            <a href="#" class="btn btn-success">

                <i class="bi bi-file-earmark-excel me-1"></i>

                Excel

            </a>

            <a href="#" class="btn btn-danger">

                <i class="bi bi-file-earmark-pdf me-1"></i>

                PDF

            </a>

            <button class="btn btn-secondary" onclick="window.print()">

                <i class="bi bi-printer me-1"></i>

                Print

            </button>
        -->

        </div>

    </div>

    <form method="GET">

        <div class="card shadow-sm mb-4">

            <div class="card-body">

                <div class="row">

                    <div class="col-md-10">

                        <label class="form-label">

                            Period

                        </label>

                        <select class="form-select" name="period_id">

                            @foreach($periods as $period)

                            <option value="{{ $period->id }}" @selected($selectedPeriod==$period->id)>

                                {{ $period->name }}

                            </option>

                            @endforeach

                        </select>

                    </div>

                    <div class="col-md-2 d-grid">

                        <label>&nbsp;</label>

                        <button class="btn btn-primary">

                            <i class="bi bi-search"></i>

                            Filter

                        </button>

                    </div>

                </div>

            </div>

        </div>

    </form>

    @if($abc)

    <div class="row mb-4">

        <div class="col-md-3">

            <div class="card border-start border-success border-4">

                <div class="card-body">

                    <small class="text-muted">

                        Best Fitness

                    </small>

                    <h3>

                        {{ number_format($abc->fitness,6) }}

                    </h3>

                </div>

            </div>

        </div>

        <div class="col-md-3">

            <div class="card border-start border-primary border-4">

                <div class="card-body">

                    <small class="text-muted">

                        Population

                    </small>

                    <h3>

                        {{ $abc->population_size }}

                    </h3>

                </div>

            </div>

        </div>

        <div class="col-md-3">

            <div class="card border-start border-warning border-4">

                <div class="card-body">

                    <small class="text-muted">

                        Iteration

                    </small>

                    <h3>

                        {{ $abc->max_iteration }}

                    </h3>

                </div>

            </div>

        </div>

        <div class="col-md-3">

            <div class="card border-start border-danger border-4">

                <div class="card-body">

                    <small class="text-muted">

                        Execution Time

                    </small>

                    <h3>

                        {{ number_format($abc->execution_time,2) }} s

                    </h3>

                </div>

            </div>

        </div>

    </div>

    <div class="card shadow-sm">

        <div class="card-header">

            <strong>

                Optimized KPI Weights

            </strong>

        </div>

        <div class="card-body">

            <table class="table table-bordered table-hover">

                <thead class="table-light">

                    <tr>

                        <th width="60">#</th>

                        <th>KPI Master</th>

                        <th width="200">

                            Optimized Weight (%)

                        </th>

                    </tr>

                </thead>

                <tbody>

                    @foreach($abc->details as $detail)

                    <tr>

                        <td>

                            {{ $loop->iteration }}

                        </td>

                        <td>

                            {{ $detail->kpiMaster->name }}

                        </td>

                        <td>

                            {{ number_format($detail->weight,2) }}

                        </td>

                    </tr>

                    @endforeach

                </tbody>

            </table>

        </div>

    </div>

    @else

    <div class="card">

        <div class="card-body text-center py-5">

            <i class="bi bi-award display-4 text-muted"></i>

            <h5 class="mt-3">

                Best Solution Not Available

            </h5>

            <p class="text-muted">

                No ABC optimization marked as the best solution for the selected period.

            </p>

        </div>

    </div>

    @endif

</div>

@endsection