@extends('layouts.admin.app')

@section('title', 'Division Performance')

@section('content')

<div class="container-fluid">

    {{-- Header --}}
    <div class="row mb-3">

        <div class="col-md-6">

            <h3 class="fw-bold mb-1">
                Division Performance Dashboard
            </h3>

            <p class="text-muted mb-0">
                Division performance analysis based on KPI Final Score generated by Artificial Bee Colony.
            </p>

        </div>

        <div class="col-md-6">

            <form method="GET" action="{{ route('division-performance.index') }}">

                <div class="row g-2">

                    <div class="col-md-8">

                        <select name="period_id" class="form-select select2">

                            @foreach($periods as $period)

                            <option value="{{ $period->id }}" @selected($periodId==$period->id)>

                                {{ $period->name }}

                            </option>

                            @endforeach

                        </select>

                    </div>

                    <div class="col-md-4">

                        <button class="btn btn-primary w-100">

                            <i class="fa fa-search me-1"></i>

                            Filter

                        </button>

                    </div>

                </div>

            </form>

        </div>

    </div>


    {{-- Summary Card --}}

    <div class="row">

        <div class="col-lg-3 col-md-6 mb-4">

            <div class="card border-0 shadow-sm h-100">

                <div class="card-body">

                    <div class="d-flex justify-content-between">

                        <div>

                            <small class="text-muted">
                                Total Division
                            </small>

                            <h2 class="fw-bold mt-2">

                                {{ $summary['total_division'] }}

                            </h2>

                        </div>

                        <div>

                            <div class="rounded-circle bg-primary text-white d-flex align-items-center justify-content-center"
                                style="width:60px;height:60px;">

                                <i class="fa fa-building fa-2x"></i>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>


        <div class="col-lg-3 col-md-6 mb-4">

            <div class="card border-0 shadow-sm h-100">

                <div class="card-body">

                    <div class="d-flex justify-content-between">

                        <div>

                            <small class="text-muted">
                                Total Employee
                            </small>

                            <h2 class="fw-bold mt-2">

                                {{ number_format($summary['total_employee']) }}

                            </h2>

                        </div>

                        <div>

                            <div class="rounded-circle bg-success text-white d-flex align-items-center justify-content-center"
                                style="width:60px;height:60px;">

                                <i class="fa fa-users fa-2x"></i>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>


        <div class="col-lg-3 col-md-6 mb-4">

            <div class="card border-0 shadow-sm h-100">

                <div class="card-body">

                    <div class="d-flex justify-content-between">

                        <div>

                            <small class="text-muted">

                                Average KPI

                            </small>

                            <h2 class="fw-bold mt-2">

                                {{ number_format($summary['average_score'],2) }}

                            </h2>

                        </div>

                        <div>

                            <div class="rounded-circle bg-warning text-white d-flex align-items-center justify-content-center"
                                style="width:60px;height:60px;">

                                <i class="fa fa-chart-line fa-2x"></i>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>


        <div class="col-lg-3 col-md-6 mb-4">

            <div class="card border-0 shadow-sm h-100">

                <div class="card-body">

                    <div class="d-flex justify-content-between">

                        <div>

                            <small class="text-muted">

                                Best Division

                            </small>

                            <h5 class="fw-bold mt-3">

                                {{ $summary['best_division'] ?? '-' }}

                            </h5>

                        </div>

                        <div>

                            <div class="rounded-circle bg-danger text-white d-flex align-items-center justify-content-center"
                                style="width:60px;height:60px;">

                                <i class="fa fa-trophy fa-2x"></i>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>


    {{-- Ranking Division --}}
    <div class="row">

        <div class="col-lg-8">

            <div class="card shadow-sm border-0 mb-3">

                <div class="card-header bg-white">

                    <h5 class="mb-0 fw-bold">

                        Division Ranking

                    </h5>

                </div>

                <div class="card-body">

                    <div class="table-responsive">

                        <table class="table table-hover table-bordered align-middle">

                            <thead class="table-light">

                                <tr>

                                    <th width="60">
                                        Rank
                                    </th>

                                    <th>
                                        Division
                                    </th>

                                    <th width="120" class="text-center">
                                        Employee
                                    </th>

                                    <th width="150" class="text-center">
                                        Average KPI
                                    </th>

                                    <th width="220">
                                        Performance
                                    </th>

                                    <th width="130" class="text-center">
                                        Category
                                    </th>

                                    <th width="90" class="text-center">
                                        Action
                                    </th>

                                </tr>

                            </thead>

                            <tbody>

                                @forelse($divisions as $division)

                                @php

                                $rank = $loop->iteration;

                                $score = $division->average_score ?? 0;

                                if($score >= 90){

                                $badge='success';
                                $category='Excellent';

                                }elseif($score >=80){

                                $badge='primary';
                                $category='Very Good';

                                }elseif($score >=70){

                                $badge='info';
                                $category='Good';

                                }elseif($score >=60){

                                $badge='warning';
                                $category='Fair';

                                }else{

                                $badge='danger';
                                $category='Poor';

                                }

                                @endphp

                                <tr>

                                    <td class="text-center fw-bold">

                                        {{ $rank }}

                                    </td>

                                    <td>

                                        <strong>

                                            {{ $division->name }}

                                        </strong>

                                    </td>

                                    <td class="text-center">

                                        {{ $division->total_employee }}

                                    </td>

                                    <td class="text-center">

                                        <span class="fw-bold">

                                            {{ number_format($score,2) }}

                                        </span>

                                    </td>

                                    <td>

                                        <div class="progress" style="height:22px;">

                                            <div class="progress-bar bg-{{ $badge }}"
                                                style="width: {{ min($score,100) }}%;">

                                                {{ number_format($score,1) }} %

                                            </div>

                                        </div>

                                    </td>

                                    <td class="text-center">

                                        <span class="badge bg-{{ $badge }}">

                                            {{ $category }}

                                        </span>

                                    </td>

                                    <td class="text-center">

                                        <a href="{{ route('division-performance.show',$division->id) }}?period_id={{ $periodId }}"
                                            class="btn btn-sm btn-primary">

                                            <i class="fa fa-eye"></i>

                                        </a>

                                    </td>

                                </tr>

                                @empty

                                <tr>

                                    <td colspan="7" class="text-center text-muted py-4">

                                        No data available.

                                    </td>

                                </tr>

                                @endforelse

                            </tbody>

                        </table>

                    </div>

                </div>

            </div>


            <div class="card shadow-sm border-0">

                <div class="card-header bg-white">

                    <h5 class="mb-0 fw-bold">

                        Average KPI by Division

                    </h5>

                </div>

                <div class="card-body">

                    <canvas id="divisionBarChart" height="230">

                    </canvas>

                </div>

            </div>

        </div>


        {{-- Chart --}}

        <div class="col-lg-4">

            <div class="card shadow-sm border-0 mb-4">

                <div class="card-header bg-white">

                    <h5 class="mb-0 fw-bold">

                        KPI Distribution

                    </h5>

                </div>

                <div class="card-body">

                    <canvas id="divisionPieChart" height="260">

                    </canvas>

                </div>

            </div>

            <div class="card shadow-sm border-0">

                <div class="card-header bg-white">

                    <h5 class="mb-0 fw-bold">

                        Performance Summary

                    </h5>

                </div>

                <div class="card-body">

                    @foreach($divisions as $division)

                    @php

                    $score = $division->average_score ?? 0;

                    @endphp

                    <div class="mb-3">

                        <div class="d-flex justify-content-between">

                            <small>

                                {{ $division->name }}

                            </small>

                            <strong>

                                {{ number_format($score,1) }}

                            </strong>

                        </div>

                        <div class="progress" style="height:10px;">

                            <div class="progress-bar" style="width: {{ min($score,100) }}%;">

                            </div>

                        </div>

                    </div>

                    @endforeach

                </div>

            </div>

        </div>

    </div>



</div>

@endsection


@push('scripts')

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
    $(function(){
    
        $('.select2').select2({
    
            theme:'bootstrap-5',
    
            width:'100%',
    
            placeholder:'Select Period'
    
        });
    
    });
    
    
    const divisionLabels = [
    
        @foreach($divisions as $division)
    
            "{{ $division->name }}",
    
        @endforeach
    
    ];
    
    
    const divisionScores = [
    
        @foreach($divisions as $division)
    
            {{ $division->average_score ?? 0 }},
    
        @endforeach
    
    ];
    
    
    const divisionEmployees = [
    
        @foreach($divisions as $division)
    
            {{ $division->total_employee }},
    
        @endforeach
    
    ];
    
    
    
    /*
    |--------------------------------------------------------------------------
    | Average KPI Chart
    |--------------------------------------------------------------------------
    */
    
    new Chart(
    
        document.getElementById('divisionBarChart'),
    
        {
    
            type:'bar',
    
            data:{
    
                labels:divisionLabels,
    
                datasets:[{
    
                    label:'Average KPI',
    
                    data:divisionScores
    
                }]
    
            },
    
            options:{
    
                responsive:true,
    
                maintainAspectRatio:false,
    
                plugins:{
    
                    legend:{
    
                        display:false
    
                    }
    
                },
    
                scales:{
    
                    y:{
    
                        beginAtZero:true,
    
                        max:100
    
                    }
    
                }
    
            }
    
        }
    
    );
    
    
    
    /*
    |--------------------------------------------------------------------------
    | Employee Distribution
    |--------------------------------------------------------------------------
    */
    
    new Chart(
    
        document.getElementById('divisionPieChart'),
    
        {
    
            type:'doughnut',
    
            data:{
    
                labels:divisionLabels,
    
                datasets:[{
    
                    data:divisionEmployees
    
                }]
    
            },
    
            options:{
    
                responsive:true,
    
                maintainAspectRatio:false,
    
                plugins:{
    
                    legend:{
    
                        position:'bottom'
    
                    }
    
                }
    
            }
    
        }
    
    );
    
</script>

@endpush